version: "3.8"
services:
  app:
    build: ./docker/app
    container_name: app
    volumes:
      - ./src:/var/www
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network

  db:
    build: ./docker/db
    container_name: db
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_root_password
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "3306:3306"
    networks:
      - app-network

  web:
    build: ./docker/web
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
